### ISSUE TITLE
roslaunch problem on ubuntu 16.04 

### ISSUE THREAD

**Issue by auvilink** [furushchev/respeaker_ros#8]
Hi, Mr. Furuta

In order to just make this work, I switched to a freshly installed Ubuntu 16.04 x86_64 + ROS 

After carefully follow all the instructions, the roslaunch line spins out this error:

Traceback (most recent call last):
  File "/home/asa/catkin_ws/src/respeaker_ros/scripts/respeaker_node.py", line 385, in <module>
    n = RespeakerNode()
  File "/home/asa/catkin_ws/src/respeaker_ros/scripts/respeaker_node.py", line 284, in __init__
    self.dyn_srv = Server(RespeakerConfig, self.on_config)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/server.py", line 81, in __init__
    self._change_config(self.config, ~0)  # Consistent with the C++ API, the callback gets called with level=~0 (i.e. -1)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/server.py", line 104, in _change_config
    self.config = self.callback(config, level)
  File "/home/asa/catkin_ws/src/respeaker_ros/scripts/respeaker_node.py", line 314, in on_config
    config[name] = self.respeaker.read(name)
  File "/home/asa/catkin_ws/src/respeaker_ros/scripts/respeaker_node.py", line 140, in read
    response = struct.unpack(b'ii', response.tostring())
struct.error: unpack requires a string argument of length 8
[respeaker_node-2] process has died [pid 77173, exit code 1, cmd /home/asa/catkin_ws/src/respeaker_ros/scripts/respeaker_node.py __name:=respeaker_node __log:=/home/asa/.ros/log/ed105888-7003-11e8-a5dc-000c297e350d/respeaker_node-2.log].
log file: /home/asa/.ros/log/ed105888-7003-11e8-a5dc-000c297e350d/respeaker_node-2*.log

Did you happen to test it on ubuntu 16.04 ?

Thanks.

**Comment by auvilink** [comment]
#!/usr/bin/env python
#
# WARNING!!
# This file is automatically generated.
# DO NOT MODIFY THIS FILE!
#
# To generate this file, please run:
# cd /path/to/this/package
# python ./scripts/respeaker_gencfg.py
#

from dynamic_reconfigure.parameter_generator_catkin import *

gen = ParameterGenerator()

#       name    type     level     description     default      min      max
gen.add("STATNOISEONOFF", bool_t, 0, "Stationary noise suppression. 0 = OFF 1 = ON", True)
gen.add("GAMMA_ETAIL", double_t, 0, "Over-subtraction factor of echo (tail components). min .. max attenuation", 1.000000, 0.000000, 3.000000)
gen.add("AGCTIME", double_t, 0, "Ramps-up / down time-constant in seconds.", 0.982401, 0.100000, 1.000000)
gen.add("GAMMA_NS_SR", double_t, 0, "Over-subtraction factor of stationary noise for ASR.  [0.0 .. 3.0] (default: 1.0)", 1.000000, 0.000000, 3.000000)
gen.add("AGCDESIREDLEVEL", double_t, 0, "Target power level of the output signal.  [-inf .. 0] dBov (default: -23dBov = 10log10(0.005))", 0.005000, 0.000000, 0.990000)
gen.add("MIN_NN_SR", double_t, 0, "Gain-floor for non-stationary noise suppression for ASR. [-inf .. 0] dB (default: -10dB = 20log10(0.3))", 0.300000, 0.000000, 1.000000)
gen.add("STATNOISEONOFF_SR", bool_t, 0, "Stationary noise suppression for ASR. 0 = OFF 1 = ON", True)
gen.add("MIN_NS_SR", double_t, 0, "Gain-floor for stationary noise suppression for ASR. [-inf .. 0] dB (default: -16dB = 20log10(0.15))", 0.150000, 0.000000, 1.000000)
gen.add("GAMMA_ENL", double_t, 0, "Over-subtraction factor of non-linear echo. min .. max attenuation", 1.000000, 0.000000, 5.000000)
gen.add("NLAEC_MODE", int_t, 0, "Non-Linear AEC training mode. 0 = OFF 1 = ON - phase 1 2 = ON - phase 2", 0, 0, 2)
gen.add("TRANSIENTONOFF", bool_t, 0, "Transient echo suppression. 0 = OFF 1 = ON", True)
gen.add("RT60ONOFF", bool_t, 0, "RT60 Estimation for AES. 0 = OFF 1 = ON", True)
gen.add("AGCGAIN", double_t, 0, "Current AGC gain factor.  [0 .. 60] dB (default: 0.0dB = 20log10(1.0))", 11.119642, 1.000000, 1000.000000)
gen.add("NONSTATNOISEONOFF", bool_t, 0, "Non-stationary noise suppression. 0 = OFF 1 = ON", True)
gen.add("AECFREEZEONOFF", bool_t, 0, "Adaptive Echo Canceler updates inhibit. 0 = Adaptation enabled 1 = Freeze adaptation, filter only", False)
gen.add("AGCMAXGAIN", double_t, 0, "Maximum AGC gain factor.  [0 .. 60] dB (default 30dB = 20log10(31.6))", 31.600000, 1.000000, 1000.000000)
gen.add("CNIONOFF", bool_t, 0, "Comfort Noise Insertion. 0 = OFF 1 = ON", True)
gen.add("NONSTATNOISEONOFF_SR", bool_t, 0, "Non-stationary noise suppression for ASR. 0 = OFF 1 = ON", True)
gen.add("NLATTENONOFF", bool_t, 0, "Non-Linear echo attenuation. 0 = OFF 1 = ON", False)
gen.add("ECHOONOFF", bool_t, 0, "Echo suppression. 0 = OFF 1 = ON", True)
gen.add("AECNORM", double_t, 0, "Limit on norm of AEC filter coefficients", 2.000000, 0.250000, 16.000000)
gen.add("AECSILENCELEVEL", double_t, 0, "Threshold for signal detection in AEC [-inf .. 0] dBov (Default: -80dBov = 10log10(1x10-8))", 0.000000, 0.000000, 1.000000)
gen.add("GAMMA_E", double_t, 0, "Over-subtraction factor of echo (direct and early components). min .. max attenuation", 1.000000, 0.000000, 3.000000)
gen.add("FREEZEONOFF", bool_t, 0, "Adaptive beamformer updates. 0 = Adaptation enabled 1 = Freeze adaptation, filter only", False)
gen.add("AGCONOFF", bool_t, 0, "Automatic Gain Control.  0 = OFF  1 = ON", True)
gen.add("MIN_NN", double_t, 0, "Gain-floor for non-stationary noise suppression. [-inf .. 0] dB (default: -10dB = 20log10(0.3))", 0.300000, 0.000000, 1.000000)
gen.add("MIN_NS", double_t, 0, "Gain-floor for stationary noise suppression. [-inf .. 0] dB (default: -16dB = 20log10(0.15))", 0.150000, 0.000000, 1.000000)
gen.add("GAMMA_NS", double_t, 0, "Over-subtraction factor of stationary noise. min .. max attenuation", 1.000000, 0.000000, 3.000000)
gen.add("HPFONOFF", int_t, 0, "High-pass Filter on microphone signals. 0 = OFF 1 = ON - 70 Hz cut-off 2 = ON - 125 Hz cut-off 3 = ON - 180 Hz cut-off", 1, 0, 3)
gen.add("GAMMAVAD_SR", double_t, 0, "Set the threshold for voice activity detection. [-inf .. 60] dB (default: 3.5dB 20log10(1.5))", 15.000000, 0.000000, 1000.000000)
gen.add("GAMMA_NN", double_t, 0, "Over-subtraction factor of non- stationary noise. min .. max attenuation", 1.100000, 0.000000, 3.000000)
gen.add("GAMMA_NN_SR", double_t, 0, "Over-subtraction factor of non-stationary noise for ASR.  [0.0 .. 3.0] (default: 1.1)", 1.100000, 0.000000, 3.000000)

exit(gen.generate("respaker_ros", "respeaker_ros", "Respeaker"))

**Comment by auvilink** [comment]
BTW, I try to re-enerate this file but has errors, maybe this will help debugging?

python ./scripts/respeaker_gencfg.py
Traceback (most recent call last):
  File "./scripts/respeaker_gencfg.py", line 7, in <module>
    from respeaker_node import PARAMETERS, init_respeaker
ImportError: cannot import name init_respeaker

**Comment by furushchev** [comment]
The config file looks fine.
I found that the node failed on reading current configuration from your device.
Did you successfully read parameters from your device? (e.g. `python tuning.py -p` in https://github.com/respeaker/usb_4_mic_array )

I tested and works fine on our Ubuntu 14.04 / 16.04 x86_64.

**Comment by auvilink** [comment]
python tuning.py -p
name			type	max	min	r/w	info
-------------------------------
AECFREEZEONOFF  	int	1	0	rw	Adaptive Echo Canceler updates inhibit.
                                                            0 = Adaptation enabled
                                                            1 = Freeze adaptation, filter only
AECNORM         	float	16	0.25	rw	Limit on norm of AEC filter coefficients
AECPATHCHANGE   	int	1	0	ro	AEC Path Change Detection.
                                                            0 = false (no path change detected)
                                                            1 = true (path change detected)
AECSILENCELEVEL 	float	1	1e-09	rw	Threshold for signal detection in AEC [-inf .. 0] dBov (Default: -80dBov = 10log10(1x10-8))
AECSILENCEMODE  	int	1	0	ro	AEC far-end silence detection status. 
                                                            0 = false (signal detected) 
                                                            1 = true (silence detected)
AGCDESIREDLEVEL 	float	0.99	1e-08	rw	Target power level of the output signal. 
                                                            [−inf .. 0] dBov (default: −23dBov = 10log10(0.005))
AGCGAIN         	float	1000	1	rw	Current AGC gain factor. 
                                                            [0 .. 60] dB (default: 0.0dB = 20log10(1.0))
AGCMAXGAIN      	float	1000	1	rw	Maximum AGC gain factor. 
                                                            [0 .. 60] dB (default 30dB = 20log10(31.6))
AGCONOFF        	int	1	0	rw	Automatic Gain Control. 
                                                            0 = OFF 
                                                            1 = ON
AGCTIME         	float	1	0.1	rw	Ramps-up / down time-constant in seconds.
CNIONOFF        	int	1	0	rw	Comfort Noise Insertion.
                                                            0 = OFF
                                                            1 = ON
DOAANGLE        	int	359	0	ro	DOA angle. Current value. Orientation depends on build configuration.
ECHOONOFF       	int	1	0	rw	Echo suppression.
                                                            0 = OFF
                                                            1 = ON
FREEZEONOFF     	int	1	0	rw	Adaptive beamformer updates.
                                                            0 = Adaptation enabled
                                                            1 = Freeze adaptation, filter only
FSBPATHCHANGE   	int	1	0	ro	FSB Path Change Detection.
                                                            0 = false (no path change detected)
                                                            1 = true (path change detected)
FSBUPDATED      	int	1	0	ro	FSB Update Decision.
                                                            0 = false (FSB was not updated)
                                                            1 = true (FSB was updated)
GAMMAVAD_SR     	float	1000	0	rw	Set the threshold for voice activity detection.
                                                            [−inf .. 60] dB (default: 3.5dB 20log10(1.5))
GAMMA_E         	float	3	0	rw	Over-subtraction factor of echo (direct and early components). min .. max attenuation
GAMMA_ENL       	float	5	0	rw	Over-subtraction factor of non-linear echo. min .. max attenuation
GAMMA_ETAIL     	float	3	0	rw	Over-subtraction factor of echo (tail components). min .. max attenuation
GAMMA_NN        	float	3	0	rw	Over-subtraction factor of non- stationary noise. min .. max attenuation
GAMMA_NN_SR     	float	3	0	rw	Over-subtraction factor of non-stationary noise for ASR. 
                                                            [0.0 .. 3.0] (default: 1.1)
GAMMA_NS        	float	3	0	rw	Over-subtraction factor of stationary noise. min .. max attenuation
GAMMA_NS_SR     	float	3	0	rw	Over-subtraction factor of stationary noise for ASR. 
                                                            [0.0 .. 3.0] (default: 1.0)
HPFONOFF        	int	3	0	rw	High-pass Filter on microphone signals.
                                                            0 = OFF
                                                            1 = ON - 70 Hz cut-off
                                                            2 = ON - 125 Hz cut-off
                                                            3 = ON - 180 Hz cut-off
MIN_NN          	float	1	0	rw	Gain-floor for non-stationary noise suppression.
                                                            [−inf .. 0] dB (default: −10dB = 20log10(0.3))
MIN_NN_SR       	float	1	0	rw	Gain-floor for non-stationary noise suppression for ASR.
                                                            [−inf .. 0] dB (default: −10dB = 20log10(0.3))
MIN_NS          	float	1	0	rw	Gain-floor for stationary noise suppression.
                                                            [−inf .. 0] dB (default: −16dB = 20log10(0.15))
MIN_NS_SR       	float	1	0	rw	Gain-floor for stationary noise suppression for ASR.
                                                            [−inf .. 0] dB (default: −16dB = 20log10(0.15))
NLAEC_MODE      	int	2	0	rw	Non-Linear AEC training mode.
                                                            0 = OFF
                                                            1 = ON - phase 1
                                                            2 = ON - phase 2
NLATTENONOFF    	int	1	0	rw	Non-Linear echo attenuation.
                                                            0 = OFF
                                                            1 = ON
NONSTATNOISEONOFF	int	1	0	rw	Non-stationary noise suppression.
                                                            0 = OFF
                                                            1 = ON
NONSTATNOISEONOFF_SR	int	1	0	rw	Non-stationary noise suppression for ASR.
                                                            0 = OFF
                                                            1 = ON
RT60            	float	0.9	0.25	ro	Current RT60 estimate in seconds
RT60ONOFF       	int	1	0	rw	RT60 Estimation for AES. 0 = OFF 1 = ON
SPEECHDETECTED  	int	1	0	ro	Speech detection status.
                                                            0 = false (no speech detected)
                                                            1 = true (speech detected)
STATNOISEONOFF  	int	1	0	rw	Stationary noise suppression.
                                                            0 = OFF
                                                            1 = ON
STATNOISEONOFF_SR	int	1	0	rw	Stationary noise suppression for ASR.
                                                            0 = OFF
                                                            1 = ON
TRANSIENTONOFF  	int	1	0	rw	Transient echo suppression.
                                                            0 = OFF
                                                            1 = ON
VOICEACTIVITY   	int	1	0	ro	VAD voice activity status.
                                                            0 = false (no voice activity)
                                                            1 = true (voice activity)

**Comment by auvilink** [comment]
I reinstalled the ubuntu 16.04 x86_64 and tried again and this time it seems the firmware update got trouble, have you ever had this issue?

sudo python dfu.py --download 6_channels_firmware.bin
entering dfu mode
found dfu device
downloading
Traceback (most recent call last):
  File "dfu.py", line 229, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "dfu.py", line 224, in main
    dev.revertfactory()
  File "dfu.py", line 210, in __exit__
    self.leave()   
  File "dfu.py", line 204, in leave
    return self._out_request(self.XMOS_DFU_RESETFROMDFU)
  File "dfu.py", line 175, in _out_request
    request, value, self.interface, data, self.TIMEOUT)
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 1043, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 883, in ctrl_transfer
    timeout))
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 5] Input/Output Error

**Comment by auvilink** [comment]
I am using a linux virtual machine and this could be the issue.

**Comment by kintzhao** [comment]
How to work it on linux virtual machine  @furushchev
